### ISSUE TITLE
Empty search

### ISSUE THREAD

**Issue by gherghel** [2alin/tabFx#15]

**Comment by gherghel** [comment]
It came back.
The search function does not work (it is empty) though I have hundreds of tabs.
Reinstall the application does not help.
W11
Firefox 124

Reinstall the application does not help.

It worked fine untill today.



See  search #14 

[empty search.docx](https://github.com/2alin/tabFx/files/14228757/empty.search.docx)

**Comment by gherghel** [comment]
It healed itself on the next update of Firefox.

**Comment by 2alin** [comment]
@gherghel Similar to #14, Firefox nightly versions may be prone to have issues with any extension before reaching beta phase (Firefox developer version). I, unfortunately, cannot support and fix issues that are at least present in Firefox developer version.

I'll close this issue as it's no more present. Thanks for reporting.
